
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8024
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: {}


