name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
      - uses: actions/checkout@v4

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: docker build -t bookapp:latest

      - name: saving artifact
        run: docker save bookapp:latest | gzip > bookapp.tar.gz

      - name: uplaod arttifact
        uses: actions/upload-artifact@v4
        with:
          name: bookapp-image
          path: bookapp.tar.gz
